// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleComment: typeof import('./../views/components/blog/ArticleComment.vue')['default']
    ArticleList: typeof import('./../views/components/blog/ArticleList.vue')['default']
    ArticleMarkdownPreview: typeof import('./../views/components/blog/ArticleMarkdownPreview.vue')['default']
    BlogMenu: typeof import('./../layouts/components/header/BlogMenu.vue')['default']
    CommentItem: typeof import('./../views/components/blog/CommentItem.vue')['default']
    CustomMdEditor: typeof import('./../components/CustomMdEditor/index.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    Footer: typeof import('./../layouts/components/footer/index.vue')['default']
    Header: typeof import('./../layouts/components/header/index.vue')['default']
    MdComment: typeof import('./../components/CustomMdEditor/MdComment.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
  }
}
