// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../layout/components/AppFooter.vue')['default']
    AppHeader: typeof import('./../layout/components/AppHeader.vue')['default']
    AppMain: typeof import('./../layout/components/AppMain.vue')['default']
    'Clarity:languageLine': typeof import('~icons/clarity/language-line')['default']
    DarkMode: typeof import('./../components/DarkMode/index.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    'Ep:menu': typeof import('~icons/ep/menu')['default']
    'Ep:moon': typeof import('~icons/ep/moon')['default']
    'Ep:plus': typeof import('~icons/ep/plus')['default']
    'Ep:sunny': typeof import('~icons/ep/sunny')['default']
    'Ep:switch': typeof import('~icons/ep/switch')['default']
    'Ic:roundLanguage': typeof import('~icons/ic/round-language')['default']
    Icon: typeof import('~icons/ic/on')['default']
    IconifyIcon: typeof import('~icons/ic/onify-icon')['default']
    IFrame: typeof import('./../components/iFrame/index.vue')['default']
    LangSelect: typeof import('./../components/LangSelect/index.vue')['default']
    Pagination: typeof import('./../components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
  }
}
